name 'ignite_test'
maintainer 'Mark Van de Vyver'
maintainer_email 'mark@taqtiqa.com'
license 'Apache-2.0'
description 'installs Weaveworks Ignite using test recipes'
version '0.1.0'

depends 'docker'
depends 'etcd'
depends 'ignite'
